# Default hyperparams (CLI overrides take precedence)
seed: 42
global_batch: 64
micro_batch: 8
lr: 3.0e-4
weight_decay: 0.1
betas: [0.9, 0.95]
eps: 1.0e-8
warmup_steps: 2000
train_steps: 10000
eval_every: 500
save_every: 1000
fp16: true
bf16: false
log_interval: 50
model:
  d_model: 768
  n_layers: 10
  n_heads: 12
  dropout: 0.0
