[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Stage-1"
version = "0.1.0"
description = "Stage-1 Vertex AI training package for Liquid LLM"
requires-python = ">=3.10"
dependencies = [
    "torch==2.3.1",
    "einops==0.8.0",
    "numpy==1.26.4",
    "tqdm==4.66.4",
    "pyyaml==6.0.2",
    "transformers>=4.42.0",
    "accelerate>=0.30.0",
    "sentencepiece>=0.2.0",
    "datasets>=2.20.0",
    "huggingface_hub>=0.23.0",
    "tokenizers>=0.15.2",
    "google-cloud-storage>=2.17.0",
    "google-cloud-secret-manager>=2.20.0",
    "python-json-logger>=3.2.1",
]

[tool.setuptools]
package-dir = {"" = "Stage_1"}
packages = {find = {where = ["."], include = ["Stage_1*", "trainer*"]}}
include-package-data = true

[tool.setuptools.package-data]
"Stage_1" = [
    "configs/*.yaml",
    "configs/*.jsonl",
    "runbooks/*.txt",
    "monitoring/*.yaml",
    "monitoring/*.json",
    "data/**/*.json",
]

[project.scripts]
stage1-train = "Stage_1.cli:main"
